<!-- BEGIN LOAD CONTENT-->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
            <ol class="breadcrumb page-breadcrumb pull-left box-menu">
                <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                </li>
                <li class="active">Dashboard</li>
            </ol>
		</div>
		
		
        <div class="row">
            <div class="col-md-12">
                <div class="card card-topline-green">
                    <div class="card-head">
                        <header>Transporter Compliance</header>
                        <div class="tools">
                            <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                            <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                            <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="card-body ">
                        <!-- start widget -->
                        <!--
                        <div class="row">
                            <div class="state-overview">
                                <div class="col-lg-4 col-sm-6">
                                    <div class="overview-panel green">
                                        <div class="symbol">
                                            <i class="fa fa-folder-open"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="14">0</p>
                                            <p>VALID GPS</p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-4 col-sm-6">
                                    <div class="overview-panel red">
                                        <div class="symbol">
                                            <i class="fa fa-spinner"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="3421">0</p>
                                            <p>LATE GPS SHARING</p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-4 col-sm-6">
                                    <div class="overview-panel red">
                                        <div class="symbol">
                                            <i class="fa fa-file-text"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="23">0</p>
                                            <p>EARLY GPS STOP</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="state-overview">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel blue">
                                        <div class="symbol">
                                            <i class="fa fa-file-text"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="23">0</p>
                                            <p>EARLY GPS STOP</p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel purple">
                                        <div class="symbol">
                                            <i class="fa fa-file-text"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="23">0</p>
                                            <p>EARLY GPS STOP</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="state-overview">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel yellow">
                                        <div class="symbol">
                                            <i class="fa fa-file-text"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="23">0</p>
                                            <p>EARLY GPS STOP</p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel orange">
                                        <div class="symbol">
                                            <i class="fa fa-file-text"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="23">0</p>
                                            <p>EARLY GPS STOP</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="state-overview">
                                <div class="col-lg-6 col-sm-6">
                                    <div class="overview-panel green">
                                        <div class="symbol">
                                            <i class="fa fa-folder-open"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="14">0</p>
                                            <p>VALID GPS</p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-6 col-sm-6">
                                    <div class="overview-panel red">
                                        <div class="symbol">
                                            <i class="fa fa-spinner"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="3421">0</p>
                                            <p>LATE GPS SHARING</p>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            
                            
                        </div>
                        -->
                        
                        <div class="row">
                            <div class="state-overview">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel blue">
                                        <div class="symbol">
                                            <i class="fa fa-file-text"></i>
                                        </div>
                                        <div class="value white">
                                            <p>EMKL</p>
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="180">180</p>
                                            
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel purple">
                                        <div class="symbol">
                                            <i class="fa fa-truck"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="70">70</p>
                                            <p>DEPO</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="state-overview">
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel yellow">
                                        <div class="symbol">
                                            <i class="icon-magnet"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="35">35</p>
                                            <p>UOI</p>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-3 col-sm-6">
                                    <div class="overview-panel orange">
                                        <div class="symbol">
                                            <i class="fa fa-ship"></i>
                                        </div>
                                        <div class="value white">
                                            <p class="sbold addr-font-h1" data-counter="counterup" data-value="50">50</p>
                                            <p>CY BELAWAN</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end widget -->
                        
                        <div class="row">
                            <div class="col-lg-3 col-sm-3">
	                            <div class="white-box border-gray">
                                    <div class="stats-row">
                                        <div class="stat-item">
                                            <h6><b>EMKL (Assign To)</b></div>
                                        <div class="stat-item">
                                            <h6>Shipment</h6> <b>100</b></div>
                                        <div class="stat-item">
                                            <h6>Assign</h6> <b>80</b></div>
                                    </div>
                                </div>
	                        </div>
                                
                            <div class="col-lg-3 col-sm-3">
	                            <div class="white-box border-gray">
                                    <div class="stats-row">
                                        <div class="stat-item">
                                            <h6><b>DEPO (In Progress)</b></div>
                                        <div class="stat-item">
                                            <h6>Pickup</h6> <b>50</b></div>
                                        <div class="stat-item">
                                            <h6>Depo</h6> <b>20</b></div>
                                    </div>

                                </div>
	                        </div>
                            
                            <div class="col-lg-3 col-sm-3">
	                            <div class="white-box border-gray">
                                    <div class="stats-row">
                                        <div class="stat-item">
                                            <h6><b>UOI (Loading)</b></div>
                                        <div class="stat-item">
                                            <h6>In Journey</h6> <b>10</b></div>
                                        <div class="stat-item">
                                            <h6>UOI</h6> <b>15</b></div>
                                    </div>
                                </div>
	                        </div>
                            
                            <div class="col-lg-3 col-sm-3">
	                            <div class="white-box border-gray">
                                    <div class="stats-row">
                                        <div class="stat-item">
                                            <h6><b>CY BELAWAN</b></div>
                                        <div class="stat-item">
                                            <h6>Delivery</h6> <b>30</b></div>
                                        <div class="stat-item">
                                            <h6>Complete</h6> <b>20</b></div>
                                    </div>
                                </div>
	                        </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        
        
        <!-- chart start -->
        <div class="row">
            <div class="col-md-12">
                <div class="card card-topline-red">
                    <div class="card-head">
                        <header>SHIPMENT TREND</header>
                        <div class="tools">
                            <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                            <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                            <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                        </div>
                    </div>
                    <div class="card-body no-padding height-9">
                        <div class="row">
                            <div id="echarts_line" style="height: 500px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Chart end -->
		 
	</div>
</div>
<!-- END LOAD CONTENT-->