<?php
use Zend\Mvc\Application;
?>

<!--
<?= $this->doctype() ?>
<html>
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'public/img/favicon.ico'])
    ?>

    <!-- BEGIN GOOGLE FONT -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <!-- END GOOGLE FONT -->

    <!-- BEGIN ICONS -->
    <link href="<?=$this->basePath('public');?>/assets/js/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <!-- END ICONS -->
    
    <!-- BEGIN BOOTSTRAP -->
    <link href="<?=$this->basePath('public');?>/assets/js/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- END BOOTSTRAP -->
    <link rel="stylesheet" href="<?=$this->basePath('public');?>/assets/css/login.css">
    
</head>
<body>
    <div class="form-title">
        <h1><?= $this->message ?></h1>
    </div>
    <!-- Login Form-->
    <div class="page-404-form text-center">
        <div class="toggle"><a href="index.html"><i class="fa fa-times white-color"></i></a>
        </div>
        <div class="form">
            <h1>404</h1>
            
            <?php if (! empty($this->reason)) :
                switch ($this->reason) {
                    case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
                        $reasonMessage = 'The requested controller was unable to dispatch the request.';
                        break;
                    case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
                        $reasonMessage = 'The requested middleware was unable to dispatch the request.';
                        break;
                    case Application::ERROR_CONTROLLER_NOT_FOUND:
                        $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
                        break;
                    case Application::ERROR_CONTROLLER_INVALID:
                        $reasonMessage = 'The requested controller was not dispatchable.';
                        break;
                    case Application::ERROR_ROUTER_NO_MATCH:
                        $reasonMessage = 'The requested URL could not be matched by routing.';
                        break;
                    default:
                        $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
                        break;
                }
            ?>
            <h3><?= $this->message ?></h3>
            <p><?= $reasonMessage ?></p>
            
            <p></p>
            <?php endif ?>
            
            <form>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
			<button class="btn btn-default" type="button">Go!</button>
		  </span>
                </div>
            </form>
            <div class="ContactSupport"><a href="javascript:void(0)">Contact Support</a>
            </div>
        </div>
    </div>
    <!-- start js include path -->
    <script src="<?=$this->basePath('public');?>/assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/pages.js" type="text/javascript"></script>
    <!-- end js include path -->
</body>
</html>


<h1>A 404 error occurred</h1>
<h2><?= $this->message ?></h2>

<?php if (! empty($this->reason)) :
    switch ($this->reason) {
        case Application::ERROR_CONTROLLER_CANNOT_DISPATCH:
            $reasonMessage = 'The requested controller was unable to dispatch the request.';
            break;
        case Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH:
            $reasonMessage = 'The requested middleware was unable to dispatch the request.';
            break;
        case Application::ERROR_CONTROLLER_NOT_FOUND:
            $reasonMessage = 'The requested controller could not be mapped to an existing controller class.';
            break;
        case Application::ERROR_CONTROLLER_INVALID:
            $reasonMessage = 'The requested controller was not dispatchable.';
            break;
        case Application::ERROR_ROUTER_NO_MATCH:
            $reasonMessage = 'The requested URL could not be matched by routing.';
            break;
        default:
            $reasonMessage = 'We cannot determine at this time why a 404 was generated.';
            break;
    }
?>
<p><?= $reasonMessage ?></p>
<?php endif ?>

<?php if (! empty($this->controller)) : ?>
<dl>
    <dt>Controller:</dt>
    <dd>
        <?= $this->escapeHtml($this->controller) ?>
        <?php
        if (! empty($this->controller_class) && $this->controller_class != $this->controller) {
            printf('(resolves to %s)', $this->escapeHtml($this->controller_class));
        }
        ?>
    </dd>
</dl>
<?php endif ?>

<?php if (! empty($this->display_exceptions)) : ?>
    <?php if (isset($this->exception)
        && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
<hr/>

<h2>Additional information:</h2>
<h3><?= get_class($this->exception) ?></h3>
<dl>
    <dt>File:</dt>
    <dd>
        <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt>Message:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
    </dd>
    <dt>Stack trace:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>

        <?php if ($ex = $this->exception->getPrevious()) : ?>
<hr/>

<h2>Previous exceptions:</h2>
<ul class="list-unstyled">
            <?php $icount = 0 ?>
            <?php while ($ex) : ?>
    <li>
        <h3><?= get_class($ex) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
                <?php
                $ex = $ex->getPrevious();
                if (++$icount >= 50) {
                    echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
                    break;
                }
                ?>
            <?php endwhile ?>
</ul>
        <?php endif ?>
    <?php else : ?>
<h3>No Exception available</h3>
    <?php endif ?>
<?php endif ?>

