<!-- BEGIN HEADER -->
 <div class="page-header navbar navbar-fixed-top">
	<div class="page-header-inner ">
	
		<!-- logo start -->
		<div class="page-logo">
			<a href="javascript:;">
				<img src="<?=$this->basePath('public');?>/assets/img/logo.png" alt="logo" class="logo-default" />
			</a>
			<div class="menu-toggler sidebar-toggler">
				<span></span>
			</div>
		</div>
		<!-- logo end -->

		<!-- start mobile menu -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
			<span></span>
		</a>
	   <!-- end mobile menu -->
	   
		<!-- start header menu -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
				
				<!-- start notification dropdown -->
				<li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<i class="fa fa-bell-o"></i>
						<span class="badge orange-bgcolor"> 6 </span>
					</a>
					<ul class="dropdown-menu">
						<li class="external">
							<h3><span class="bold">Notifications</span></h3>
							<span class="notification-label purple-bgcolor">New 6</span>
						</li>
						<li>
							<ul class="dropdown-menu-list small-slimscroll-style" data-handle-color="#637283">
								<li>
									<a href="javascript:;">
										<span class="time">just now</span>
										<span class="details">
										<span class="notification-icon circle green-bgcolor"><i class="fa fa-check"></i></span> Congratulations!. </span>
									</a>
								</li>
								<li>
									<a href="javascript:;">
										<span class="time">3 mins</span>
										<span class="details">
										<span class="notification-icon circle purple-bgcolor"><i class="fa fa-user o"></i></span>
										<b>John Micle </b>is now following you. </span>
									</a>
								</li>
								<li>
									<a href="javascript:;">
										<span class="time">7 mins</span>
										<span class="details">
										<span class="notification-icon circle blue-bgcolor"><i class="fa fa-comments-o"></i></span>
										<b>Sneha Jogi </b>sent you a message. </span>
									</a>
								</li>
								<li>
									<a href="javascript:;">
										<span class="time">12 mins</span>
										<span class="details">
										<span class="notification-icon circle pink"><i class="fa fa-heart"></i></span>
										<b>Ravi Patel </b>like your photo. </span>
									</a>
								</li>
								<li>
									<a href="javascript:;">
										<span class="time">15 mins</span>
										<span class="details">
										<span class="notification-icon circle yellow"><i class="fa fa-warning"></i></span> Warning! </span>
									</a>
								</li>
								<li>
									<a href="javascript:;">
										<span class="time">10 hrs</span>
										<span class="details">
										<span class="notification-icon circle red"><i class="fa fa-times"></i></span> Application error. </span>
									</a>
								</li>
							</ul>
							<div class="dropdown-menu-footer">
								<a href="javascript:void(0)"> All notifications </a>
							</div>
						</li>
					</ul>
				</li>
				<!-- end notification dropdown -->
				<!-- start message dropdown -->
				<li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<i class="fa fa-envelope-o"></i>
						<span class="badge cyan-bgcolor"> 2 </span>
					</a>
					<ul class="dropdown-menu">
						<li class="external">
							<h3><span class="bold">Messages</span></h3>
							<span class="notification-label cyan-bgcolor">New 2</span>
						</li>
						<li>
							<ul class="dropdown-menu-list small-slimscroll-style" data-handle-color="#637283">
								<li>
									<a href="#">
										<span class="subject">
											<span class="from"> Sarah Smith </span>
											<span class="time">Just Now </span>
										</span>
										<span class="message"> Jatin I found you on LinkedIn... </span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="subject">
											<span class="from"> John Deo </span>
											<span class="time">16 mins </span>
										</span>
										<span class="message"> Fwd: Important Notice Regarding Your Domain Name... </span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="subject">
											<span class="from"> Rajesh </span>
											<span class="time">2 hrs </span>
										</span>
										<span class="message"> pls take a print of attachments. </span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="subject">
											<span class="from"> Lina Smith </span>
											<span class="time">40 mins </span>
										</span>
										<span class="message"> Apply for Ortho Surgeon </span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="subject">
											<span class="from"> Jacob Ryan </span>
											<span class="time">46 mins </span>
										</span>
										<span class="message"> Request for leave application. </span>
									</a>
								</li>
							</ul>
							<div class="dropdown-menu-footer">
								<a href="#"> All Messages </a>
							</div>
						</li>
					</ul>
				</li>
				<!-- end message dropdown -->
				
				
				<!-- start manage user dropdown -->
				<li class="dropdown dropdown-user">
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<img class="img-circle" src="<?=$this->basePath('public');?>/assets/img/user/user1.svg" height="29" width="29" />
						<span class="username username-hide-on-mobile">
							Testing - Oke  
						</span>
						<i class="fa fa-angle-down"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-default">
						<li>
							<a data-href="#" class="ajaxify">
								<i class="icon-user"></i> Profile 
							</a>
						</li>
						
						<li>
							<a href="javascript:;">
								<i class="icon-directions"></i> Help
							</a>
						</li>
						<li class="divider"> </li>
						<li>
							<a href="javascript:;">
								<i class="icon-lock"></i> Lock
							</a>
						</li>
						<li>
							<a href="<?=$this->basePath();?>/logout">
								<i class="icon-logout"></i> Log Out 
							</a>
						</li>
					</ul>
				</li>
				<!-- end manage user dropdown -->
				<li class="dropdown dropdown-quick-sidebar-toggler">
					<a href="javascript:;" class="dropdown-toggle">
						<i class="icon-logout"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<!-- END HEADER -->
<div class="clearfix"></div>