<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('EasyGo-GPS')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'public/img/favicon.ico'])
    ?>

    <!-- BEGIN GOOGLE FONT -->
	<link href="<?=$this->basePath('public');?>/assets/css/fonts.googleapis.css" rel="stylesheet" type="text/css"/>
    <!-- END GOOGLE FONT -->

    <!-- BEGIN ICONS -->
    <link href="<?=$this->basePath('public');?>/assets/js/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <!-- END ICONS -->

    <script src="<?=$this->basePath('public');?>/jspath.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/jquery.min.js" type="text/javascript"></script>

    <!-- BEGIN BOOTSTRAP -->
    <link href="<?=$this->basePath('public');?>/assets/js/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="<?=$this->basePath('public');?>/assets/js/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    <link href="<?=$this->basePath('public');?>/assets/js/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <script src="<?=$this->basePath('public');?>/assets/js/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <!-- END BOOTSTRAP -->

    <!-- BEGIN THEME STYLE -->
    <link href="<?=$this->basePath('public');?>/assets/css/theme_style.css" rel="stylesheet" id="rt_style_components" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/style.css" rel="stylesheet" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/components.css" id="style_components" rel="stylesheet" type="text/css" />
    <!-- END THEME STYLE -->

    <!-- BEGIN JS JQUERY -->
    <script src="<?=$this->basePath('public');?>/assets/js/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/jquery.cokie.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/jquery.slimscroll.js"></script>
    <!-- END JS JQUERY -->

    <!-- BEGIN GOOGLE MAP -->
	<!--
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCWqaKWKtKtqZ8SV40A-hx8s2hDiNHFeWA&callback=initMap&sensor=false"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/mapmarker.jquery.js" type="text/javascript"></script>
	-->
    <!-- END GOOGLE MAP -->

    <!-- BEGIN JS CHART -->
    <!--
    <script src="<?=$this->basePath('public');?>/assets/js/echarts/echarts.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/echarts/echart-data.js" type="text/javascript"></script>
    -->
    <!-- END JS CHART -->   

    <!-- BEGIN JS COUNTERUP -->
    <link href="<?=$this->basePath('public');?>/assets/js/morris/morris.css" rel="stylesheet" type="text/css" />
    <script src="<?=$this->basePath('public');?>/assets/js/moment.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/counterup/jquery.waypoints.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/counterup/jquery.counterup.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/sparkline/jquery.sparkline.js" type="text/javascript"></script>
    <!-- END JS COUNTERUP -->

    <!-- BEGIN SWEET ALERT -->
    <link href="<?=$this->basePath('public');?>/assets/js/sweetalert/sweetalert.css" rel="stylesheet" type="text/css"/>
    <script src="<?=$this->basePath('public');?>/assets/js/sweetalert/sweetalert-dev.js"></script>
    <!-- END SWEET ALERT -->

    <!-- BEGIN JS CONFIG -->
    <script src="<?=$this->basePath('public');?>/assets/js/app.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/layout.js" type="text/javascript"></script>
    <!-- END JS CONFIG -->

</head>
    
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md">
	<div class="page-wrapper">
		<?=$this->partial("layout/header")?>
   		
   		<div class="page-container">
			<?=$this->partial("layout/slidebar")?>
    	    <?=$this->content ?>
   		</div>
   		<?= $this->partial("layout/footer")?>
	</div>
</body>
</html>
