<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('EasyGo-GPS | Login')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('public') . '/img/favicon.ico'])
    ?>
    
    <!-- BEGIN GOOGLE FONT -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <!-- END GOOGLE FONT -->

    <!-- BEGIN ICONS -->
    <link href="<?=$this->basePath('public');?>/assets/js/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="<?=$this->basePath('public');?>/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <!-- END ICONS -->

    <script src="<?=$this->basePath('public');?>/jspath.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/jquery.min.js" type="text/javascript"></script>
    
    <!-- BEGIN BOOTSTRAP -->
    <link href="<?=$this->basePath('public');?>/assets/js/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="<?=$this->basePath('public');?>/assets/js/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

    <link href="<?=$this->basePath('public');?>/assets/js/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <script src="<?=$this->basePath('public');?>/assets/js/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <!-- END BOOTSTRAP -->
        

    <link rel="stylesheet" href="<?=$this->basePath('public');?>/assets/css/login.css">
    <script src="<?=$this->basePath('public');?>/assets/js/login.js"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/pages.js" type="text/javascript"></script>


    <script src="<?=$this->basePath('public');?>/assets/js/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>

    <!--- SweetAlert-->
    <link href="<?=$this->basePath('public');?>/assets/js/sweetalert/sweetalert.css" rel="stylesheet" type="text/css"/>
    <script src="<?=$this->basePath('public');?>/assets/js/sweetalert/sweetalert-dev.js"></script>
    <!--- SweetAlert-->

    <script src="<?=$this->basePath('public');?>/assets/js/login-validation.js" type="text/javascript"></script>
    <script src="<?=$this->basePath('public');?>/assets/js/app.js" type="text/javascript"></script>
    <!-- end js include path -->

    <script language="javascript">
        $(document).ready(function() {
            width = $( window ).width();
            if(width <= 480){
                $(".login-form").css("max-width", "360px");
                $(".login-form").css("width", "350px");
            }

            $(window).bind('resize', function() {
                width = $( window ).width();
                if(width <= 480){
                    $(".login-form").css("max-width", "360px");
                    $(".login-form").css("width", "350px");
                }else{
                    $(".login-form").css("max-width", "510px");
                    $(".login-form").css("width", "500px");
                }
            });
        });
    </script>
</head>

    
<body>
    <div class="form-logo"></div>
	
    <div class="form-title">
        <!--<h2 style="color: grey; font-size: 12px;"></h2>-->
    </div>
	
    <!-- Login Form-->
    <div class="login-form text-center">
        <div class="toggle"></div>
        <div class="form formLogin">
            <h2>Silahkan Login</h2>
            <form method="post" action="<?=$this->basePath();?>/auth" id="login_validation" class="form-horizontal">
                
                <div class="form-body">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-user"></i>
                            </span>
                            <input 	type="text" 
                                    class="form-control" 
                                    name="username" 
                                    id="username"
                                    data-rule-required="true"
                                    size="26" 
                                    minlength ="1" 
                                    placeholder="Username" />
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="fa fa-lock"></i>
                            </span>
                            <input 	type="password" 
                                    class="form-control" 
                                    name="password" 
                                    id="password" 
                                    data-rule-required="true"
                                    size="26"
                                    minlength="1" 
                                    placeholder="Password" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="remember text-left">
                            <div class="checkbox checkbox-primary">
                                <input 	type="checkbox" 
                                        class="checkbox"
                                        name="rememberme" 
                                        id="rememberme" 
                                        value="1" />
                                <label for="checkbox2">
                                    Remember me
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success uppercase pull-right">Login</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</body>
</html>